name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby (installs .ruby-version, runs bundle install)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test
        run: bundle exec --verbose rspec
